//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.BillTable = new HashSet<BillTable>();
        }
    
        public int DishId { get; set; }
        public string DishName { get; set; }
        public Nullable<int> DishPrice { get; set; }
    
        public virtual ICollection<BillTable> BillTable { get; set; }
    }
}
