//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.BillTable = new HashSet<BillTable>();
        }
    
        public int TableId { get; set; }
        public string TableStatus { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public Nullable<int> NumberOfDishes { get; set; }
        public Nullable<int> WaiterId { get; set; }
    
        public virtual ICollection<BillTable> BillTable { get; set; }
        public virtual Waiter Waiter { get; set; }
    }
}
