//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resturant_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiter
    {
        public Waiter()
        {
            this.Table = new HashSet<Table>();
        }
    
        public int WaiterId { get; set; }
        public string WaiterName { get; set; }
        public Nullable<int> EarnMoney { get; set; }
        public Nullable<int> NumberOfHandleTable { get; set; }
        public string WaiterStatus { get; set; }
    
        public virtual ICollection<Table> Table { get; set; }
    }
}
